name: IITM Verification Action

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000272@ds.study.iitm.ac.in
        run: echo "Action triggered for verification"
